version: '2'
services:
  kafka:
    image: sneck/kafka
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <KAFKA_ADVERTISED_HOST_NAME>
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
    ports:
      - "9092:9092"
    restart: always
  zookeeper:
    image: sneck/zookeeper
    hostname: zookeeper
    environment:
      ZK_MYID: 1
    ports:
      - "2181:2181"
    restart: always