version: '2'
services:
  emqttd:
    image: sneck/emqttd
    environment:
      - EMQTTD_AUTO_CLUSTER_JOIN=true
      - EMQTTD_BIND_NODE_NAME=ip
    volumes:
      - cluster:/opt/emqttd/cluster
volumes:
  cluster: {}
