version: '2'
services:
  kafka-manager:
    image: sneck/kafka-manager
    hostname: kafka-manager
    links:
      - zookeeper
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    restart: always
  kafka:
    image: sneck/kafka
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.0.3"
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
    ports:
      - "9092:9092"
    restart: always
  zookeeper:
    image: sneck/zookeeper
    hostname: zookeeper
    environment:
      ZK_MYID: 1
    ports:
      - "2181:2181"
    restart: always